### PR TITLE
Adding hello file

### PR DESCRIPTION
**Pull request by awilkof**

### CODE REVIEW

**Comment by Borgaard** [comment]
Hello! I'm unable to merge this pull request because the `hello.rb` file isn't in your personal homework directory. 

When you type `pwd` in terminal, your `hello.rb` file should be located in `my_projects/bewd_sf_13_homework/firstnameLastname-GithubUsername`.

Right now it's located in `/my_projects/bewd_sf_13_homework`. If you haven't already, you can create your personal directory from the homework directory with `mkdir firstnameLastname-GithubUsername` and move `hello.rb` in there. You can then add, commit, and push to update your pull request.

I know Git is a lot to take in at first, so please reach out to me either on Slack or replying here if you're unsure. I'm also available 1 hour before class if you'd like to do this together.

Happy Wednesday!

**Comment by awilkof** [comment]
Hey Nicole, 

Thanks for following up - Got your notification on slack as well. I will resubmit by Monday, probably today or tomorrow. 

 -Andrea

**Comment by Borgaard** [comment]
Sounds good! 😸

**Comment by Borgaard** [comment]
Yay! Thanks for fixing this. See you in class today! 🍰

**Comment by awilkof** [comment]
Glad I was successful. Thanks!

**Pull request merged**
